
-- config-sync cherry-pick
o.bind("ALT + SHIFT + 4", "Screenshot", "omasnap")
o.bind("PRINT", "Screenshot", "omasnap")
o.bind("SUPER + ALT + KP_Enter", "Tmux", { omarchy = "terminal-tmux" })
o.bind("SUPER + ALT + SHIFT + F", "File manager (cwd)", { launch = 'flea --gui "$(omarchy-cmd-terminal-cwd)"' })
o.bind("SUPER + ALT + SLASH", "Monitor scaling down", "/home/gruper/.config/omarchy/plugins/im0001gt.screens/scripts/display-ctl scale down")
o.bind("SUPER + CTRL + ALT + 1", "Gaming room light", "omarchy-shell hass toggleEntity light.yeelight_ceilb_0x315851e4")
o.bind("SUPER + CTRL + ALT + 2", "Gaming room AC", "omarchy-shell hass toggleEntity climate.gaming_room_ac")
o.bind("SUPER + CTRL + ALT + 3", "Living room AC", "omarchy-shell hass toggleEntity climate.living_room_ac")
o.bind("SUPER + CTRL + ALT + 4", "Home door lock", "omarchy-shell hass toggleEntity lock.home_door")
o.bind("SUPER + CTRL + KP_Enter", "Herdr", { omarchy = "terminal-herdr" })
o.bind("SUPER + D", "Show desktop", "omadesk")
o.bind("SUPER + KP_Enter", "Terminal", { omarchy = "terminal" })
o.bind("SUPER + M", "Spotifast", "spotifast")
o.bind("SUPER + SHIFT + A", "Gemini", { webapp = "https://gemini.google.com" })
o.bind("SUPER + SHIFT + F", "File manager", { launch = 'flea --gui' })
o.bind("SUPER + SHIFT + KP_Enter", "Browser", { omarchy = "browser" })
o.bind("SUPER + SHIFT + S", "Screenshot", "omasnap")
o.bind("SUPER + SLASH", "Monitor scaling up", "/home/gruper/.config/omarchy/plugins/im0001gt.screens/scripts/display-ctl scale up")
